export const SPECIALIZATIONS = [
  "Budowanie masy mięśniowej",
  "Redukcja tkanki tłuszczowej",
  "Trening siłowy",
  "Trening funkcjonalny",
  "CrossFit",
  "Powerlifting",
  "Kalistenika",
  "Kettlebell",
  "Mobility",
  "Stretching",
  "Dietetyka",
  "Rehabilitacja",
  "Trening kobiet",
  "Trening seniorów",
  "Sporty walki",
  "Bieganie",
  "Triathlon",
  "Przygotowanie do zawodów",
];
